language: elixir
os:
  - linux
  #- osx
elixir:
  - 1.3
  - 1.4
otp_release:
  - 18.3
  - 19.3
env:
  - SORTED_TTL_LIST_FOLDER=/tmp/
  - SORTED_TTL_LIST_FOLDER=$HOME
script:
  - MIX_ENV=test mix test --trace
after_success:
  - MIX_ENV=test mix credo -a
  - mix coveralls.travis
sudo: false
