language: elixir
os:
  - linux
  - osx
elixir:
  - 1.3.4
  - 1.3.2
  - 1.3
otp_release:
  - 18.2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get head; fi
script:
  - MIX_ENV=test mix test --trace
after_success:
  - MIX_ENV=test mix credo -a
  - mix coveralls.travis
services:
  - redis-server
sudo: false
